# Generated by Django 3.1.7 on 2021-02-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('deposited_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('binance_api_key', models.CharField(blank=True, max_length=64, null=True)),
                ('binance_api_secret_key', models.CharField(blank=True, max_length=64, null=True)),
                ('withdrawal_address', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
